esphome:
  name: esp-smart-bojler
  friendly_name: ESP Smart Bojler

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "4zna82Nrv64UTUiWGX+myASQDkbhadCnNaD9xp1TRxQ="

ota:
  - platform: esphome
    password: "88ca75035ddaceb9ba039835022707d2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Smart-Bojler"
    password: "JjPk7Z5q1ul4"

captive_portal:
    