esphome:
  name: esp-smart-bojler
  friendly_name: ESP Smart Bojler

esp32:
  board: esp32dev
  framework:
    type: arduino

substitutions:
  mac_water_heater: FE:E2:6C:65:4A:62     # Tady bude MAC adresa Bluetooth bojleru

external_components:
  - source: 
      type: git
      url: https://github.com/pedobry/esphome-smartboiler
    components: [smartboiler]



# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "3hsR4/vg+RAkfqpsyC94StF6Adx6FzNmucVgf+wKnts="

ble_client:
  - mac_address: ${mac_water_heater}
    id: drazice_okhe

ota:
  - platform: esphome
    password: "9667fbefc37ff3d94e0ae32100db2399"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Smart-Bojler"
    password: "EAROj41GAzHX"

captive_portal:

smartboiler:
  - ble_client_id: drazice_okhe
    temp1:
      name: "Water heater temp1"
    temp2:
      name: "Water heater temp2"
    mode:
      name: "Water heater mode"
    thermostat:
      name: "Water heater thermostat"
    heat_on:
      name: "Water heater heat"
    hdo_low_tariff:
      name: "Water heater HDO"
    pin:
      name: "Water heater PIN"
    state:
      name: "Water heater state"
    version:
      name: "Water heater version"
    b_name:
      name: "Water heater name"
    consumption:
      name: "Water heater energy"

switch:
  - platform: ble_client
    ble_client_id: drazice_okhe
    name: "Enable water heater monitoring"    